### ISSUE TITLE
Using this lib to access the dmp

### ISSUE THREAD

**Issue by ghost** [mattcarpenter/mpu6050-dmp#3]
Could you please provide an example of how to use this to get  quaternion values from the dmp.
Thanks

**Comment by mattcarpenter** [comment]
Hi @harryiliffe. This module does not currently expose a method for obtaining the quaternion values however it would not be too difficult to implement. I don't have access to a Beaglebone right now so I can't test this possible solution, but have a look at this line of code: https://github.com/mattcarpenter/mpu6050-dmp/blob/master/src/binding.cc#L103

The quaternion values are read and stored in a `Quaternion` class instance. You could expose a `GetQuaternion` method on the module, similar to how the `GetRotation` (https://github.com/mattcarpenter/mpu6050-dmp/blob/master/src/binding.cc#L14) method is implemented that returns a V8 object containing the values from the `Quaternion` instance (which is `q`, as defined in this binding.h: https://github.com/mattcarpenter/mpu6050-dmp/blob/master/src/binding.h#L23)

If you can wait a week or so; I can implement this functionality and publish to the NPM registry. If you'd like to fork the repo and try implementing it yourself, i'd be happy to merge back into this module as well.

**Comment by ghost** [comment]
OK, I'll give it a go. Thanks for your help. I'm kinda new to this side of programming. I normally just blindly use the libraries. Haha.

I'll let you know how I get on.

**Comment by mseltzer94** [comment]
@mattcarpenter I made changes to be able to get the quaternion values. Let me know if you think this is the right thing to do - maybe this can help other people using the package.
